from sqlalchemy import Column, String, JSON, DateTime
from app.config.database import Base
from app.utils.time_utils import utc_now
import uuid


class OutcomeTemplate(Base):
    """
    Outcome templates for common roles.
    Each template contains 2-3 pre-written outcomes that recruiters can use as starting points.
    
    Example: A "Backend Developer" template might have outcomes like:
      - API & System Design
      - Data Handling & Performance
      - Reliability & Operations
    
    This is NOT a task template. Tasks are always generated by AI from recruiter-approved outcomes.
    """
    __tablename__ = "outcome_templates"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()), index=True)
    role_name = Column(String, nullable=False)  # e.g., "Backend Developer"
    category_slug = Column(String, nullable=False, index=True)  # e.g., "software-engineering"
    
    # Array of outcome objects: [{"title": "...", "description": "...", "default_weight": 0.33}]
    outcomes = Column(JSON, nullable=False)
    
    created_at = Column(DateTime, default=utc_now)
    updated_at = Column(DateTime, default=utc_now, onupdate=utc_now)
