"""Baseline schema for SignalStack.

This baseline captures the full current ORM schema. It is intentionally
idempotent: ``create_all`` only creates tables that do not already exist, so it
is safe to run against the existing deployed database.

Recommended usage:
  * Fresh database:      ``alembic upgrade head`` (creates every table).
  * Existing database:   ``alembic stamp head`` (mark baseline as applied
                         without touching the already-created schema).

Future schema changes should be added as new autogenerated revisions:
  ``alembic revision --autogenerate -m "describe change"``
"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "0001_baseline_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Import here so the models are registered on Base.metadata at run time.
    from app.config.database import Base
    import app.models  # noqa: F401

    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    from app.config.database import Base
    import app.models  # noqa: F401

    Base.metadata.drop_all(bind=op.get_bind())
